# Generated by Django 6.0.4 on 2026-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'étudiant', 'verbose_name_plural': 'étudiants'},
        ),
        migrations.AlterModelOptions(
            name='studentdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'document étudiant', 'verbose_name_plural': 'documents étudiants'},
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1),
        ),
    ]
