services:
  - type: web
    name: ecole-koki1
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: BREVO_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp-relay.brevo.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: DATABASE_URL
        fromService:
          type: pgsql
          name: ecole-koki1-db
          property: connectionString

databases:
  - type: pgsql
    name: ecole-koki1-db
    databaseName: ecole_koki1
