# Generated by Django 6.0.4 on 2026-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'paiement de frais', 'verbose_name_plural': 'paiements de frais'},
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['due_date'], 'verbose_name': 'structure de frais', 'verbose_name_plural': 'structures de frais'},
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('bank_transfer', 'Virement bancaire'), ('online', 'En ligne'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('partial', 'Partiel'), ('overdue', 'En retard'), ('waived', 'Exonéré')], default='pending', max_length=10),
        ),
    ]
