# Generated by Django 6.0.4 on 2026-05-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feepayment_options_alter_feestructure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('bank_transfer', 'Virement bancaire'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('online', 'En ligne'), ('other', 'Autre')], max_length=20),
        ),
    ]
