# Generated by Django 6.0.4 on 2026-05-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_feepayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_phone',
            field=models.CharField(blank=True, help_text='Numéro Wave ou Orange Money utilisé', max_length=20, verbose_name='Téléphone du payeur'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qrcodes/', verbose_name='QR Code'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=20),
        ),
    ]
