# Generated by Django 6.0.4 on 2026-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-start_date'], 'verbose_name': 'examen', 'verbose_name_plural': 'examens'},
        ),
        migrations.AlterModelOptions(
            name='examsubject',
            options={'ordering': ['subject'], 'verbose_name': "matière d'examen", 'verbose_name_plural': "matières d'examen"},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['student'], 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('unit_test', 'Test unitaire'), ('mid_term', 'Examen de mi-parcours'), ('final', 'Examen final'), ('practical', 'Pratique'), ('other', 'Autre')], max_length=20),
        ),
    ]
