# Generated by Django 6.0.4 on 2026-05-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_options_alter_examsubject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('compo_1', 'Composition 1er trimestre'), ('compo_2', 'Composition 2e trimestre'), ('compo_3', 'Composition 3e trimestre'), ('exam_final', 'Examen final'), ('other', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='max_marks',
            field=models.PositiveIntegerField(default=20, help_text='Note sur 20'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='passing_marks',
            field=models.PositiveIntegerField(default=10, help_text='Note de passage sur 20'),
        ),
    ]
