# Generated by Django 6.0.4 on 2026-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classes_assigned', models.ManyToManyField(blank=True, related_name='teachers', to='academics.class')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject')),
            ],
            options={
                'ordering': ['teacher_id'],
            },
        ),
    ]
