# Generated by Django 6.0.4 on 2026-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableslot',
            options={'ordering': ['day', 'start_time'], 'verbose_name': "créneau d'emploi du temps", 'verbose_name_plural': "créneaux d'emploi du temps"},
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.CharField(choices=[('monday', 'Lundi'), ('tuesday', 'Mardi'), ('wednesday', 'Mercredi'), ('thursday', 'Jeudi'), ('friday', 'Vendredi'), ('saturday', 'Samedi')], max_length=10),
        ),
    ]
