# Generated by Django 6.0.4 on 2026-05-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date'], 'verbose_name': 'année académique', 'verbose_name_plural': 'années académiques'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name': 'classe', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['class_obj', 'name'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'matière', 'verbose_name_plural': 'matières'},
        ),
    ]
