# Generated by Django 6.0.4 on 2026-05-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicyear_options_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['order'], 'verbose_name': 'classe', 'verbose_name_plural': 'classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordre de progression (CI=1, CP=2, CE1=3, CE2=4, CM1=5, CM2=6)'),
        ),
    ]
