# Generated by Django 6.0.4 on 2026-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'annonce', 'verbose_name_plural': 'annonces'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Tous les utilisateurs'), ('students', 'Étudiants seulement'), ('teachers', 'Enseignants seulement'), ('parents', 'Parents seulement'), ('admins', 'Administrateurs seulement')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('fee_alert', 'Alerte frais'), ('exam_alert', 'Alerte examen'), ('attendance_alert', 'Alerte présence'), ('announcement', 'Annonce')], default='info', max_length=20),
        ),
    ]
