# Generated by Django 6.0.4 on 2026-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'student'], 'verbose_name': 'enregistrement de présence', 'verbose_name_plural': 'Enregistrements de présence'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('excused', 'Excusé')], default='present', max_length=10),
        ),
    ]
